# Be sure to replace <your_subscription_key> and <your_region> with your actual
# Azure Text-to-Speech API credentials. Also, replace your_book.epub with the
# name of your EPUB file, and audiobook_output with the name of the directory
# where you want to save the output files.

# After creating and saving the `docker-compose.yml` file, run the
# `docker-compose up` command in the same directory to pull the image and start
# the conversion process.

# You can then try to modify volumes to fit your need.

version: '3'
services:
  epub_to_audiobook:
    build: .
    environment:
      # Add any environment variables needed for Coqui TTS here if necessary
    volumes:
      - ./books:/app/books  # Mount your local books directory to the container
      - ./output:/app/output  # Mount your local output directory to the container
    command: 'books/your_book.epub output/audiobook_output'
